site_name: STAC Generator
theme:
    name: 'material'
    palette:
      - scheme: 'default'
        media: '(prefers-color-scheme: light)'
        toggle:
          icon: 'material/lightbulb'
          name: "Switch to dark mode"
      - scheme: 'slate'
        media: '(prefers-color-scheme: dark)'
        primary: 'blue'
        toggle:
          icon: 'material/lightbulb-outline'
          name: 'Switch to light mode'
    features:
      - content.code.copy
      - content.code.select

nav:
  - Home: index.md
  - Quickstart: quick_start.md
  - Advanced Quickstart: advanced_quick_start.md
  - Introduction: introduction.md
  # - Metadata Examples:
  #   - Point: metadata_examples/point.md
  #   - Vector: metadata_examples/vector.md
  #   - Raster: metadata_examples/raster.md
  - API Reference:
  #   - Generator: generator.md
    - Schema: schema.md
    - Utility: utils.md
    - Extension:
      - Point:
        - Generator: extensions/point/generator.md
        - Schema: extensions/point/schema.md
      - Vector:
        - Generator: extensions/vector/generator.md
        - Schema: extensions/vector/schema.md
      - Raster:
        - Generator: extensions/raster/generator.md
        - Schema: extensions/raster/schema.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          paths: [stac_generator]
          options:
            docstring_style: sphinx
            show_source: false
            heading_level: 2
            members_order: source
            annotations_path: source

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
