site_name: STAC Generator
theme:
    name: 'material'
    palette:
      - scheme: 'default'
        media: '(prefers-color-scheme: light)'
        toggle:
          icon: 'material/lightbulb'
          name: "Switch to dark mode"
      - scheme: 'slate'
        media: '(prefers-color-scheme: dark)'
        primary: 'blue'
        toggle:
          icon: 'material/lightbulb-outline'
          name: 'Switch to light mode'

nav:
  - Home: index.md
  - API Reference:
    - Generator: generator.md
    - Schema: schema.md
    - Utility: utils.md
    # - Typing: typing.md
    - Extension:
      - Point:
        - Generator: extensions/point/generator.md
        - Schema: extensions/point/schema.md
      - Vector:
        - Generator: extensions/vector/generator.md
        - Schema: extensions/vector/schema.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          options:
            docstring_style: sphinx
            show_source: false
            heading_level: 2
            members_order: source
            annotations_path: source
