- id: "Werribee"
  location: "https://object-store.rc.nectar.org.au/v1/AUTH_2b454f47f2654ab58698afd4b4d5eba7/mccn-test-data/documentation/Werribee.geojson"
  collection_date: "2025-01-01"
  collection_time: "00:00:00"
  title: "Werribee Item"
  description: "Suburbs near Werribee Melbourne"
  column_info:
    - name: "Suburb_Name"
      description: "suburb name"
