- id: Werribee
  location: "https://object-store.rc.nectar.org.au/v1/AUTH_2b454f47f2654ab58698afd4b4d5eba7/mccn-test-data/documentation/Werribee.geojson"
  collection_date: '2025-01-01'
  collection_time: 00:00:00
  column_info:
  - description: Suburb_Name
    name: Suburb_Name
  join_config:
    file: "https://object-store.rc.nectar.org.au/v1/AUTH_2b454f47f2654ab58698afd4b4d5eba7/mccn-test-data/documentation/distance.csv"
    left_on: Suburb_Name
    right_on: Area
    column_info:
      - description: Area Name
        name: Area
      - description: Driving Distance to CBD in km
        name: Distance
      - description: Time taken to reach CBD by public transport in minutes
        name: Public_Transport
      - description: Time taken to reach CBD by driving in minutes
        name: Drive
      - description: Average 5 year growth in percentage in 2025
        name: Growth
      - description: Average rental yield in 2025
        name: Yield